kurs/Models/Company.cs
namespace kurs.Models
{
    public class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProductsCount { get; set; }
        public string ImagePath { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}

kurs/Models/Forms/CompanyForm.cs
namespace kurs.Models.Forms
{
    public class CompanyForm
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public IFormFile Image { get; set; }
    }
}

kurs/Controllers/CompaniesController.cs
using kurs.Models;
using kurs.Models.Forms;
using kurs.Services;
using Microsoft.AspNetCore.Mvc;

namespace kurs.Controllers
{
    public class CompaniesController : EntityController<Company, CompanyForm>
    {
        public CompaniesController(CompanyManager manager) : base(manager)
        {
            _filters = new List<Func<List<Company>, string, List<Company>>>
            {
                (x, s) => x.Where(e => e.Name.ToLower().Contains(s.ToLower())).ToList(),
            };
        }

        public override Task<IActionResult> Edit(CompanyForm form, int? id)
        {
            ModelState.Remove(nameof(form.Image));
            return base.Edit(form, id);
        }

    }
}

kurs/Views/Companies/Add.cshtml
@using kurs.Models.Forms;
@{
    Layout = null;
}
@model CompanyForm
<form asp-action="Add" asp-controller="Companies" enctype="multipart/form-data" onsubmit="return AjaxPost(this);">
    <div asp-validation-summary="All" hidden></div>
    <span asp-validation-for="Name" class="text-danger"></span>
    <div class="input-group mb-3">
        <input type="text" asp-for="Name" class="form-control" placeholder="Name" aria-label="Name">
    </div>
    <span asp-validation-for="Image" class="text-danger"></span>
    <div class="input-group mb-3">
        <div class="custom-file">
            <input type="file" asp-for="Image" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
            <label class="custom-file-label" for="inputGroupFile01">Choose image</label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary btn-block">Add</button>
</form>

kurs/Views/Companies/Edit.cshtml
@using kurs.Models.Forms;
@{
    Layout = null;
}
@model CompanyForm
<form asp-action="Edit" asp-controller="Companies" asp-route-id="@Model.Id" onsubmit="return AjaxPost(this);">
    <div asp-validation-summary="All" hidden></div>
    <span asp-validation-for="Name" class="text-danger"></span>
    <div class="input-group mb-3">
        <input type="text" asp-for="Name" class="form-control" placeholder="Name" aria-label="Name">
    </div>
    <span asp-validation-for="Image" class="text-danger"></span>
    <div class="input-group mb-1">
        <div class="custom-file">
            <input type="file" asp-for="Image" class="custom-file-input" id="inputGroupFile01">
            <label class="custom-file-label" for="inputGroupFile01" aria-describedby="inputGroupFileAddon01">Choose image</label>
        </div>
    </div>
    <div class="text-muted mb-3">If the image is not selected, it will not change.</div>

    <button type="submit" class="btn btn-primary btn-block">Save</button>
</form>

kurs/Views/Companies/Table.cshtml
@{
    Layout = null;
}
@model List<Company>
<div class="table-responsive mb-5">
    <table class="table table-bordered text-center mb-0">
        <thead class="bg-secondary text-dark">
            <tr>
                <th>Image</th>
                <th>Name</th>
                <th>Products Count</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody class="align-middle">
            @foreach (var company in Model)
            {
                <tr>
                    <td class="align-middle"><img src="@company.ImagePath" alt="" style="width: 50px;"></td>
                    <td class="align-middle w-50">@company.Name</td>
                    <td class="align-middle">@company.ProductsCount</td>
                    <td class="align-middle">
                        <div class="d-flex justify-content-center">
                            <button onclick="showInPopup('@Url.Action("Edit", "Companies", new { id = company.Id })', 'Edit Category')" class="btn btn-sm btn-primary"><i class="fas fa-pen"></i></button>
                            <button onclick="AjaxDelete('@Url.Action("Delete", "Companies", new { id = company.Id })')" class="btn btn-sm btn-primary" style="width: 32px"><i class="fa fa-times"></i></button>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>