kurs/Models/Country.cs
namespace kurs.Models
{
    public class Country
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<City> Cities { get; set; }
    }
}

kurs/Models/Forms/CountryForm.cs
namespace kurs.Models.Forms
{
    public class CountryForm
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

kurs/Controllers/CountriesController.cs
using kurs.Attributes;
using Microsoft.AspNetCore.Mvc;
using kurs.Services;
using kurs.Models.Forms;
using kurs.Models;

namespace kurs.Controllers
{
    public class CountriesController : EntityController<Country, CountryForm>
    {
        public CountriesController(CountryManager manager) : base(manager) 
        {
            _filters = new List<Func<List<Country>, string, List<Country>>>
            {
                (x, s) => x.Where(e => e.Name.ToLower().Contains(s.ToLower())).ToList()
            };
        }
    }
}

kurs/Views/Countries/Add.cshtml
@using kurs.Models.Forms;
@{
    Layout = null;
}
@model CountryForm
<form asp-action="Add" asp-controller="Countries" onsubmit="return AjaxPost(this);">
    <div asp-validation-summary="All" hidden></div>
    <span asp-validation-for="Name" class="text-danger"></span>
    <div class="input-group mb-3">
        <input type="text" asp-for="Name" class="form-control" placeholder="Name">
    </div>
    <button type="submit" class="btn btn-primary btn-block">Add</button>
</form>

kurs/Views/Countries/Edit.cshtml
@using kurs.Models.Forms;
@{
    Layout = null;
}
@model CountryForm
<form asp-action="Edit" asp-controller="Countries" enctype="multipart/form-data" onsubmit="return AjaxPost(this);">
    <div asp-validation-summary="All" hidden></div>
    <span asp-validation-for="Name" class="text-danger"></span>
    <div class="input-group mb-3">
        <input type="text" asp-for="Name" class="form-control" placeholder="Name">
    </div>
    <button type="submit" class="btn btn-primary btn-block">Save</button>
</form>

kurs/Views/Countries/Table.cshtml
@{
    Layout = null;
}
@model List<Country>
<div class="table-responsive mb-5">
    <table class="table table-bordered text-center mb-0">
        <thead class="bg-secondary text-dark">
            <tr>
                <th>Name</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody class="align-middle">
            @foreach (var country in Model)
            {
                <tr>
                    <td class="align-middle">@country.Name</td>
                    <td class="align-middle">
                        <div class="d-flex justify-content-center">
                            <button onclick="showInPopup('@Url.Action("Edit", "Countries", new { id = country.Id })', 'Edit Country')" class="btn btn-sm btn-primary"><i class="fas fa-pen"></i></button>
                            <button onclick="AjaxDelete('@Url.Action("Delete", "Countries", new { id = country.Id })')" class="btn btn-sm btn-primary" style="width: 32px"><i class="fa fa-times"></i></button>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>