kurs/Models/Forms/ProductForm.cs
namespace kurs.Models.Forms
{
    public class ProductForm
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public float Price { get; set; }
        public int Amount { get; set; }
        public int CategoryId { get; set; }
        public int CompanyId { get; set; }
        public List<int> TagIds { get; set; }
        public IFormFileCollection Images { get; set; }
    }
}

kurs/Models/Forms/ShippingForm.cs
namespace kurs.Models.Forms
{
    public class ShippingForm
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public float Price { get; set; }
    }
}

kurs/Models/Forms/TagForm.cs
namespace kurs.Models.Forms
{
    public class TagForm
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int TagGroupId { get; set; }
    }
}

kurs/Models/Forms/TagGroupForm.cs
namespace kurs.Models.Forms
{
    public class TagGroupForm
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

kurs/Models/Order.cs
using Microsoft.AspNetCore.Routing.Constraints;
using System.Text.RegularExpressions;

namespace kurs.Models
{
    public class Order
    {
        public int Id { get; set; }
        public float SubtotalPrice { get; set; }
        public int UserId { get; set; }
        public int ShippingId { get; set; }
        
        public virtual User User { get; set; }
        public virtual Shipping Shipping { get; set; }
        public virtual ICollection<OrderProduct> Products { get; set; }

        public float TotalPrice()
        {
            return SubtotalPrice + Shipping.Price;
        }
    }
}

kurs/Models/Product.cs
namespace kurs.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public float Price { get; set; }
        public int Amount { get; set; }
        public float Rating { get; set; }
        public int ReviewsCount { get; set; }
        public int CategoryId { get; set; }
        public int CompanyId { get; set; }

        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<ProductImage> Images { get; set; }
        public virtual ICollection<ProductTag> Tags { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}

kurs/Models/Review.cs
namespace kurs.Models
{
    public class Review
    {
        public int Id { get; set; }
        public float Rating { get; set; }
        public string Content { get; set; }
        public DateTime Date { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }

        public virtual Product Product { get; set; }
        public virtual User User { get; set; }

    }
}

kurs/Models/Shipping.cs
namespace kurs.Models
{
    public class Shipping
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public float Price { get; set; }
    }
}

kurs/Models/Tag.cs
namespace kurs.Models
{
    public class Tag
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProductsCount { get; set; }
        public int TagGroupId { get; set; }

        public virtual TagGroup TagGroup { get; set; }
    }
}

kurs/Models/TagGroup.cs
namespace kurs.Models
{
    public class TagGroup
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Tag> Tags { get; set; }
    }
}

kurs/Models/User.cs
using Microsoft.AspNetCore.Identity;

namespace kurs.Models
{
    public class User : IdentityUser<int>
    {
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Address { get; set; }
        public bool IsAdmin { get; set; }
        public int CityId { get; set; }

        public virtual City City { get; set; }
        public virtual ICollection<Order> Orders { get; set; }

        public string Fullname()
        {
            return $"{Firstname} {Lastname}";
        }

    }
}

kurs/Controllers/CitiesController.cs
using kurs.Attributes;
using Microsoft.AspNetCore.Mvc;
using kurs.Services;
using Microsoft.AspNetCore.Mvc.Filters;
using kurs.Models.Forms;
using kurs.Models;

namespace kurs.Controllers
{
    public class CitiesController : EntityController<City, CityForm>
    {
        private readonly CountryManager _countryManager;

        public CitiesController(CityManager cityManager, CountryManager countryManager) : base(cityManager)
        {
            _filters = new List<Func<List<City>, string, List<City>>>
            {
                (x, s) => x.Where(e => e.Name.ToLower().Contains(s.ToLower())).ToList(),
                (x, s) => x.Where(e => e.Country.Name.ToLower().Contains(s.ToLower())).ToList()
            };
            _countryManager = countryManager;
        }
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
            ViewBag.Countries = _countryManager.GetEntities();
        }
    }
}

kurs/Controllers/DashboardController.cs
using kurs.Attributes;
using kurs.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace kurs.Controllers
{
    public class DashboardController : Controller
    {
        private readonly DatabaseBackupManager _backupManager;

        public DashboardController(DatabaseBackupManager backupManager)
        {
            _backupManager = backupManager;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View();
        }
        [AjaxOnly]
        [Authorize(Roles = "Admin")]
        public IActionResult Backups()
        {
            return View(_backupManager.GetBackups());
        }
        [AjaxOnly]
        [Authorize(Roles = "Admin")]
        public IActionResult Backup()
        {
            _backupManager.Backup();
            return Ok();
        }
        [AjaxOnly]
        [Authorize(Roles = "Admin")]
        public IActionResult Restore(string filename)
        {
            _backupManager.Restore(filename);
            return Ok();
        }
        [AjaxOnly]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteBackup(string filename)
        {
            _backupManager.DeleteBackup(filename);
            return Ok();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Categories()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Companies()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Products()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult TagGroups()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Tags()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Countries()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Cities()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Shippings()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Reviews()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Orders()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Users()
        {
            return View();
        }
    }
}

kurs/Controllers/OrderController.cs
using kurs.Attributes;
using kurs.Models;
using kurs.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace kurs.Controllers
{
    public class OrderController : Controller
    {
        private readonly List<Func<List<Order>, string, List<Order>>> _filters;
        private readonly UserManager<User> _userManager;
        private readonly OrderManager _orderManager;
        private readonly CartManager _cartManager;

        public OrderController(UserManager<User> userManager,
                               OrderManager orderManager,
                               CartManager cartManager)
        {
            _filters = new List<Func<List<Order>, string, List<Order>>>
            {
                (x, s) => x.Where(e => e.Id == int.Parse(s)).ToList(),
                (x, s) => x.Where(e => e.User.Fullname().ToLower().Contains(s.ToLower())).ToList(),
                (x, s) => x.Where(e => e.Shipping.Name.ToLower().Contains(s.ToLower())).ToList(),
                (x, s) => x.Where(e => e.TotalPrice() >= float.Parse(s)).ToList(),
                (x, s) => x.Where(e => e.TotalPrice() <= float.Parse(s)).ToList(),
            };
            _userManager = userManager;
            _orderManager = orderManager;
            _cartManager = cartManager;
        }
        [AjaxOnly]
        public IActionResult Table(int? field, string? search)
        {
            var entities = _orderManager.GetEntities();
            if (_filters != null && !string.IsNullOrEmpty(search))
            {
                try
                {
                    entities = _filters[field ?? 0].Invoke(entities, search);
                }
                catch (Exception ex)
                {
                    return BadRequest(ex.Message);
                }
            }
            return View(entities);
        }

        [AjaxOnly]
        public async Task<IActionResult> Make()
        {
            var model = _cartManager.GetModel();
            if (model.Items.Count < 1)
            {
                return BadRequest("Your cart is empty!");
            }
            if (!User.Identity?.IsAuthenticated ?? true)
            {
                return BadRequest("To place an order, you must be logged in!");
            }
            foreach (var item in model.Items)
            {
                if (item.Product.Amount < item.Amount)
                {
                    return BadRequest($"{item.Product.Name} has only {item.Product.Amount} left!");
                }
            }

            var order = new Order
            {
                UserId = (await GetCurrentUser()).Id,
                ShippingId = model.Shipping.Id,
                SubtotalPrice = model.Items.Sum(x => x.Product.Price * x.Amount)
            };
            await _orderManager.Add(order);
            await _orderManager.AddProducts(order, model.Items);
            _cartManager.Clear();
            _cartManager.SaveChanges();
            return Ok();
        }
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            return View(_orderManager.GetEntity(id));
        }
        private async Task<User> GetCurrentUser()
        {
            return await _userManager.FindByNameAsync(User.Identity?.Name);
        }
    }
}

kurs/Controllers/ProductsController.cs
using kurs.Models;
using kurs.Models.Forms;
using kurs.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;

namespace kurs.Controllers
{
    public class ProductsController : EntityController<Product, ProductForm>
    {
        private readonly TagGroupManager _tagGroupManager;
        private readonly CompanyManager _companyManager;
        private readonly CategoryManager _categoryManager;

        public ProductsController(ProductManager manager,
                                  TagGroupManager tagGroupManager,
                                  CompanyManager companyManager,
                                  CategoryManager categoryManager) : base(manager)
        {
            _filters = new List<Func<List<Product>, string, List<Product>>>
            {
                (x, s) => x.Where(e => e.Name.ToLower().Contains(s.ToLower())).ToList(),
                (x, s) => x.Where(e => e.Description.ToLower().Contains(s.ToLower())).ToList(),
                (x, s) => x.Where(e => e.Category.Name.ToLower().Contains(s.ToLower())).ToList(),
                (x, s) => x.Where(e => e.Company.Name.ToLower().Contains(s.ToLower())).ToList(),
                (x, s) => x.Where(e => e.Tags.Select(t => t.Tag.Name.ToLower()).Contains(s.ToLower())).ToList(),
                (x, s) => x.Where(e => e.Price >= float.Parse(s)).ToList(),
                (x, s) => x.Where(e => e.Price <= float.Parse(s)).ToList(),
                (x, s) => x.Where(e => e.Amount >= int.Parse(s)).ToList(),
                (x, s) => x.Where(e => e.Amount <= int.Parse(s)).ToList(),
                (x, s) => x.Where(e => e.Rating >= float.Parse(s)).ToList(),
                (x, s) => x.Where(e => e.Rating <= float.Parse(s)).ToList(),
            };
            _tagGroupManager = tagGroupManager;
            _companyManager = companyManager;
            _categoryManager = categoryManager;
        }


        public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
            ViewBag.TagGroups = _tagGroupManager.GetEntities();
            ViewBag.Companies = _companyManager.GetEntities();
            ViewBag.Categories = _categoryManager.GetEntities();
        }
        public override Task<IActionResult> Edit(ProductForm form, int? id)
        {
            ModelState.Remove(nameof(form.Images));
            return base.Edit(form, id);
        }

    }
}

kurs/Controllers/ShippingsController.cs
using kurs.Attributes;
using Microsoft.AspNetCore.Mvc;
using kurs.Services;
using kurs.Models.Forms;
using kurs.Models;

namespace kurs.Controllers
{
    public class ShippingsController : EntityController<Shipping, ShippingForm>
    {
        public ShippingsController(ShippingManager manager) : base(manager)
        {
            _filters = new List<Func<List<Shipping>, string, List<Shipping>>>
            {
                (x, s) => x.Where(e => e.Name.ToLower().Contains(s.ToLower())).ToList(),
                (x, s) => x.Where(e => e.Price >= float.Parse(s)).ToList(),
                (x, s) => x.Where(e => e.Price <= float.Parse(s)).ToList()
            };
        }
    }
}

kurs/Controllers/TagGroupsController.cs
using kurs.Attributes;
using Microsoft.AspNetCore.Mvc;
using kurs.Services;
using kurs.Models.Forms;
using kurs.Models;

namespace kurs.Controllers
{
    public class TagGroupsController : EntityController<TagGroup, TagGroupForm>
    {
        public TagGroupsController(TagGroupManager manager) : base(manager)
        {
            _filters = new List<Func<List<TagGroup>, string, List<TagGroup>>>
            {
                (x, s) => x.Where(e => e.Name.ToLower().Contains(s.ToLower())).ToList()
            };
        }
    }
}

kurs/Controllers/TagsController.cs
using kurs.Attributes;
using Microsoft.AspNetCore.Mvc;
using kurs.Services;
using Microsoft.AspNetCore.Mvc.Filters;
using kurs.Models.Forms;
using kurs.Models;

namespace kurs.Controllers
{
    public class TagsController : EntityController<Tag, TagForm>
    {
        private readonly TagGroupManager _tagGroupManager;

        public TagsController(TagManager manager, TagGroupManager tagGroupManager) : base(manager)
        {
            _filters = new List<Func<List<Tag>, string, List<Tag>>>
            {
                (x, s) => x.Where(e => e.Name.ToLower().Contains(s.ToLower())).ToList(),
                (x, s) => x.Where(e => e.TagGroup.Name.ToLower().Contains(s.ToLower())).ToList(),
            };
            _tagGroupManager = tagGroupManager;
        }
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
            ViewBag.TagGroups = _tagGroupManager.GetEntities();
        }
    }
}

kurs/Views/Dashboard/Backups.cshtml
@{
    Layout = null;
}
@model List<FileInfo>
<div class="table-responsive mb-5">
    <table class="table table-bordered text-center mb-0">
        <thead class="bg-secondary text-dark">
            <tr>
                <th>Name</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody class="align-middle">
            @foreach (var file in Model.OrderByDescending(x => x.CreationTime))
            {
                <tr>
                    <td class="align-middle">@file.Name</td>
                    <td class="align-middle">@file.CreationTime</td>
                    <td class="align-middle">
                        <div class="d-flex justify-content-center">
                            <button onclick="restore('@file.Name');" class="btn btn-sm btn-primary"><i class="far fa-arrow-alt-circle-down"></i></button>
                            <button onclick="deleteBackup('@file.Name');" class="btn btn-sm btn-primary" style="width: 32px"><i class="fa fa-times"></i></button>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

kurs/Views/Dashboard/Categories.cshtml
@{
    ViewData["Title"] = "Categories - Dashboard";
}
<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Dashboard</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="/account">Account</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0"><a href="/dashboard">Dashboard</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Categories</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<div class="container-fluid d-flex">
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text">Field</span>
        </div>
        <select class="custom-select" name="field">
            <option value="0">Name</option>
            <option value="1">Products Count &ge;</option>
            <option value="2">Products Count &le;</option>
        </select>
        <input type="text" name="search" class="form-control w-50" placeholder="Search">
        <div class="input-group-append">
            <span class="input-group-text bg-transparent text-primary">
                <i class="fa fa-search"></i>
            </span>
        </div>
    </div>
    <button onclick="showInPopup('@Url.Action("Add", "Categories")', 'New Category')" class="btn btn-primary ml-2" style="width: 9em;">Add New</button>
</div>
<!-- Cart Start -->
<div id="container" class="container-fluid pt-5">
</div>
<!-- Cart End -->
@section Scripts {
    <script>
        $(document).ready(function () { loadTable("/Categories/Table") })
        $("#form-modal").on("success", function () { loadTable("/Categories/Table") })
        $("[name=field]").on("change", function () { loadTable("/Categories/Table") })
        $("[name=search]").on("change", function () { loadTable("/Categories/Table") })
    </script>
}

kurs/Views/Dashboard/Cities.cshtml
@{
    ViewData["Title"] = "Cities - Dashboard";
}
<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Dashboard</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="/account">Account</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0"><a href="/dashboard">Dashboard</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Cities</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<div class="container-fluid d-flex">
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text">Field</span>
        </div>
        <select class="custom-select" name="field">
            <option value="0">Name</option>
            <option value="1">Country</option>
        </select>
        <input type="text" name="search" class="form-control w-50" placeholder="Search">
        <div class="input-group-append">
            <span class="input-group-text bg-transparent text-primary">
                <i class="fa fa-search"></i>
            </span>
        </div>
    </div>
    <button onclick="showInPopup('@Url.Action("Add", "Cities")', 'New City')" class="btn btn-primary ml-2" style="width: 9em;">Add New</button>
</div>
<!-- Cart Start -->
<div id="container" class="container-fluid pt-5">
</div>
<!-- Cart End -->
@section Scripts {
    <script>
        $(document).ready(function () { loadTable"/Cities/Table") })
        $("#form-modal").on("success", function () { loadTable("/Cities/Table") })
        $("[name=field]").on("change", function () { loadTable("/Cities/Table") })
        $("[name=search]").on("change", function () { loadTable("/Cities/Table") })
    </script>
}

kurs/Views/Dashboard/Products.cshtml
@{
    ViewData["Title"] = "Products - Dashboard";
}
<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Dashboard</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="/account">Account</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0"><a href="/dashboard">Dashboard</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Products</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<div class="container-fluid d-flex">
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text">Field</span>
        </div>
        <select class="custom-select" name="field">
            <option value="0">Name</option>
            <option value="1">Description</option>
            <option value="2">Category</option>
            <option value="3">Company</option>
            <option value="4">Tags</option>
            <option value="5">Price &ge;</option>
            <option value="6">Price &le;</option>
            <option value="7">Amount &ge;</option>
            <option value="8">Amount &le;</option>
            <option value="9">Rating &ge;</option>
            <option value="10">Rating &le;</option>
        </select>
        <input type="text" name="search" class="form-control w-50" placeholder="Search">
        <div class="input-group-append">
            <span class="input-group-text bg-transparent text-primary">
                <i class="fa fa-search"></i>
            </span>
        </div>
    </div>
    <button onclick="showInPopup('@Url.Action("Add", "Products")', 'New Product')" class="btn btn-primary ml-2" style="width: 9em;">Add New</button>
</div>
<!-- Cart Start -->
<div id="container" class="container-fluid pt-5">
</div>
<!-- Cart End -->
@section Scripts {
    <script>
        $(document).ready(function () { loadTable("/Products/Table") })
        $("#form-modal").on("success", function () { loadTable("/Products/Table") })
        $("[name=field]").on("change", function () { loadTable("/Products/Table") })
        $("[name=search]").on("change", function () { loadTable("/Products/Table") })
    </script>
}

kurs/Views/Dashboard/Shippings.cshtml
@{
    ViewData["Title"] = "Shippings - Dashboard";
}
<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Dashboard</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="/account">Account</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0"><a href="/dashboard">Dashboard</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Shippings</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<div class="container-fluid d-flex">
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text">Field</span>
        </div>
        <select class="custom-select" name="field">
            <option value="0">Name</option>
            <option value="1">Price &ge;</option>
            <option value="2">Price &le;</option>
        </select>
        <input type="text" name="search" class="form-control w-50" placeholder="Search">
        <div class="input-group-append">
            <span class="input-group-text bg-transparent text-primary">
                <i class="fa fa-search"></i>
            </span>
        </div>
    </div>
    <button onclick="showInPopup('@Url.Action("Add", "Shippings")', 'New Shipping')" class="btn btn-primary ml-2" style="width: 9em;">Add New</button>
</div>
<!-- Cart Start -->
<div id="container" class="container-fluid pt-5">
</div>
<!-- Cart End -->
@section Scripts {
    <script>
        $(document).ready(function () { loadTable("/Shippings/Table") })
        $("#form-modal").on("success", function () { loadTable("/Shippings/Table") })
        $("[name=field]").on("change", function () { loadTable("/Shippings/Table") })
        $("[name=search]").on("change", function () { loadTable("/Shippings/Table") })
    </script>
}

kurs/Views/Dashboard/TagGroups.cshtml
@{
    ViewData["Title"] = "Tag Groups - Dashboard";
}
<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Dashboard</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="/account">Account</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0"><a href="/dashboard">Dashboard</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Tag Groups</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<div class="container-fluid d-flex">
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text">Field</span>
        </div>
        <select class="custom-select" name="field">
            <option value="0">Name</option>
        </select>
        <input type="text" name="search" class="form-control w-50" placeholder="Search">
        <div class="input-group-append">
            <span class="input-group-text bg-transparent text-primary">
                <i class="fa fa-search"></i>
            </span>
        </div>
    </div>
    <button onclick="showInPopup('@Url.Action("Add", "TagGroups")', 'New Tag Groups')" class="btn btn-primary ml-2" style="width: 9em;">Add New</button>
</div>
<!-- Cart Start -->
<div id="container" class="container-fluid pt-5">
</div>
<!-- Cart End -->
@section Scripts {
    <script>
        $(document).ready(function () { loadTable("/TagGroups/Table") })
        $("#form-modal").on("success", function () { loadTable("/TagGroups/Table") })
        $("[name=field]").on("change", function () { loadTable("/TagGroups/Table") })
        $("[name=search]").on("change", function () { loadTable("/TagGroups/Table") })
    </script>
}

kurs/Views/Dashboard/Tags.cshtml
@{
    ViewData["Title"] = "Tags - Dashboard";
}
<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">Dashboard</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="/account">Account</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0"><a href="/dashboard">Dashboard</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Tags</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<div class="container-fluid d-flex">
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text">Field</span>
        </div>
        <select class="custom-select" name="field">
            <option value="0">Name</option>
            <option value="1">Tag Group</option>
        </select>
        <input type="text" name="search" class="form-control w-50" placeholder="Search">
        <div class="input-group-append">
            <span class="input-group-text bg-transparent text-primary">
                <i class="fa fa-search"></i>
            </span>
        </div>
    </div>
    <button onclick="showInPopup('@Url.Action("Add", "Tags")', 'New Tag')" class="btn btn-primary ml-2" style="width: 9em;">Add New</button>
</div>
<!-- Cart Start -->
<div id="container" class="container-fluid pt-5">
</div>
<!-- Cart End -->
@section Scripts {
    <script>
        $(document).ready(function () { loadTable("/Tags/Table") })
        $("#form-modal").on("success", function () { loadTable("/Tags/Table") })
        $("[name=field]").on("change", function () { loadTable("/Tags/Table") })
        $("[name=search]").on("change", function () { loadTable("/Tags/Table") })
    </script>
}